SportSchoolApplication/Controllers/AboutCompetitionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SportSchoolApplication.Models;

namespace SportSchoolApplication.Controllers
{
    public class AboutCompetitionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AboutCompetitions
        public ActionResult Index()
        {
            return View(db.AboutCompetitions.ToList());
        }

        // GET: AboutCompetitions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AboutCompetition aboutCompetition = db.AboutCompetitions.Find(id);
            if (aboutCompetition == null)
            {
                return HttpNotFound();
            }
            return View(aboutCompetition);
        }

        // GET: AboutCompetitions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AboutCompetitions/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Abreviature,Name,DateFrom,DateTo,Place,Description")]  HttpPostedFileBase FilePath, AboutCompetition aboutCompetition)
        {
            if (ModelState.IsValid)
            {
                if (FilePath != null)
                {
                    string filename = FilePath.FileName;
                    FilePath.SaveAs(Server.MapPath("/Files/" + filename));
                    aboutCompetition.FilePath = "/Files/" + filename;
                }
                db.AboutCompetitions.Add(aboutCompetition);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aboutCompetition);
        }

        // GET: AboutCompetitions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AboutCompetition aboutCompetition = db.AboutCompetitions.Find(id);
            if (aboutCompetition == null)
            {
                return HttpNotFound();
            }
            return View(aboutCompetition);
        }

        // POST: AboutCompetitions/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Abreviature,Name,DateFrom,DateTo,Place,Description")] HttpPostedFileBase FilePath, AboutCompetition aboutCompetition, string oldFilePath)
        {
            if (ModelState.IsValid)
            {
                if (FilePath != null)
                {
                    string filename = FilePath.FileName;
                    FilePath.SaveAs(Server.MapPath("/Files/" + filename));
                    aboutCompetition.FilePath = "/Files/" + filename;
                }
                else aboutCompetition.FilePath = oldFilePath;

                db.Entry(aboutCompetition).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aboutCompetition);
        }

        // GET: AboutCompetitions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AboutCompetition aboutCompetition = db.AboutCompetitions.Find(id);
            if (aboutCompetition == null)
            {
                return HttpNotFound();
            }
            return View(aboutCompetition);
        }

        // POST: AboutCompetitions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AboutCompetition aboutCompetition = db.AboutCompetitions.Find(id);
            db.AboutCompetitions.Remove(aboutCompetition);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SportSchoolApplication/Views/AboutCompetitions/Create.cshtml
@model SportSchoolApplication.Models.AboutCompetition

@{
    ViewBag.Title = "О соревнованиях";
}

<h2>О соревнованиях</h2>

@using (Html.BeginForm("Create", "AboutCompetitions", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Добавить информацию о соревнованиях</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Abreviature, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Abreviature, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Abreviature, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateFrom, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateFrom, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateFrom, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateTo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateTo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateTo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Place, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Place, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Place, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FilePath, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FilePath, new { htmlAttributes = new { type = "file", required = "required" } })
            @Html.ValidationMessageFor(model => model.FilePath, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Добавить" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

SportSchoolApplication/Views/AboutCompetitions/Delete.cshtml
@model SportSchoolApplication.Models.AboutCompetition

@{
    ViewBag.Title = "О соревнованиях";
}

<h2>О соревнованиях</h2>

<h3>Вы правда хотите удалить запись?</h3>
<div>
    <h4>Удаление записи</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Abreviature)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Abreviature)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateFrom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateFrom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Place)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Place)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FilePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FilePath)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Назад", "Index")
        </div>
    }
</div>

SportSchoolApplication/Views/AboutCompetitions/Details.cshtml
@model SportSchoolApplication.Models.AboutCompetition

@{
    ViewBag.Title = "О соревнованиях";
}

<h2>О соревнованиях</h2>

<div>
    <h4>Детали:</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Abreviature)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Abreviature)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateFrom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateFrom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Place)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Place)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FilePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FilePath)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Назад", "Index")
</p>

SportSchoolApplication/Views/AboutCompetitions/Edit.cshtml
@model SportSchoolApplication.Models.AboutCompetition

@{
    ViewBag.Title = "О соревнованиях";
    string oldFilePath = Model.FilePath;
}
<h2>О соревнованиях</h2>


@using (Html.BeginForm("Edit", "AboutCompetitions", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Редактирование записи</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Abreviature, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Abreviature, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Abreviature, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateFrom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateFrom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateFrom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateTo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateTo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Place, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Place, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Place, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FilePath, new { htmlAttributes = new { type = "file", required = "required" } })
                @Html.ValidationMessageFor(model => model.FilePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

SportSchoolApplication/Views/AboutCompetitions/Index.cshtml
@model IEnumerable<SportSchoolApplication.Models.AboutCompetition>

@{
    ViewBag.Title = "О соревнованиях";
}

<h2>О соревнованиях</h2>

<p>
    @Html.ActionLink("Добваить запись", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Abreviature)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateFrom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateTo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Place)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FilePath)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Abreviature)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateFrom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateTo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Place)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a href=@item.FilePath>Скачать</a>
            </td>
            <td>
                @Html.ActionLink("Редактировать", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Детали", "Details", new { id = item.Id }) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>