SportSchoolApplication/Controllers/FPRInFacesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SportSchoolApplication.Models;

namespace SportSchoolApplication.Controllers
{
    public class FPRInFacesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: FPRInFaces
        public ActionResult Index()
        {
            return View(db.FPRInFaces.ToList());
        }

        // GET: FPRInFaces/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FPRInFace fPRInFace = db.FPRInFaces.Find(id);
            if (fPRInFace == null)
            {
                return HttpNotFound();
            }
            return View(fPRInFace);
        }

        // GET: FPRInFaces/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FPRInFaces/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FIO,Biography,Achivments")] HttpPostedFileBase PhotoPath, FPRInFace fPRInFace)
        {
            if (ModelState.IsValid)
            {
                if (PhotoPath != null)
                {
                    string filename = PhotoPath.FileName;
                    PhotoPath.SaveAs(Server.MapPath("/Images/FPRInFace/" + filename));
                    fPRInFace.PhotoPath = "/Images/FPRInFace/" + filename;
                }
                db.FPRInFaces.Add(fPRInFace);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(fPRInFace);
        }

        // GET: FPRInFaces/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FPRInFace fPRInFace = db.FPRInFaces.Find(id);
            if (fPRInFace == null)
            {
                return HttpNotFound();
            }
            return View(fPRInFace);
        }

        // POST: FPRInFaces/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FIO,Biography,Achivments")] HttpPostedFileBase PhotoPath, FPRInFace fPRInFace, string oldPhotoPath)
        {
            if (ModelState.IsValid)
            {
                if (PhotoPath != null)
                {
                    string filename = PhotoPath.FileName;
                    PhotoPath.SaveAs(Server.MapPath("/Images/FPRInFace/" + filename));
                    fPRInFace.PhotoPath = "/Images/FPRInFace/" + filename;
                }
                else fPRInFace.PhotoPath = oldPhotoPath;

                db.Entry(fPRInFace).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(fPRInFace);
        }

        // GET: FPRInFaces/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FPRInFace fPRInFace = db.FPRInFaces.Find(id);
            if (fPRInFace == null)
            {
                return HttpNotFound();
            }
            return View(fPRInFace);
        }

        // POST: FPRInFaces/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FPRInFace fPRInFace = db.FPRInFaces.Find(id);
            db.FPRInFaces.Remove(fPRInFace);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SportSchoolApplication/Views/FPRInFaces/Create.cshtml
@model SportSchoolApplication.Models.FPRInFace

@{
    ViewBag.Title = "ФПР в лицах";
    
}

<h2>ФПР в лицах</h2>

@using (Html.BeginForm("Create", "FPRInFaces", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Добавить информацию</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.FIO, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FIO, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FIO, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Biography, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <textarea name="Biography" rows="5" class="form-control"></textarea>
            @Html.ValidationMessageFor(model => model.Biography, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Achivments, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <textarea name="Achivments" rows="5" class="form-control"></textarea>
            @Html.ValidationMessageFor(model => model.Achivments, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IsCoach, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IsCoach, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IsCoach, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PhotoPath, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PhotoPath, new { htmlAttributes = new { type = "file", required = "required" } })
            @Html.ValidationMessageFor(model => model.PhotoPath, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Добавить" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

SportSchoolApplication/Views/FPRInFaces/Delete.cshtml
@model SportSchoolApplication.Models.FPRInFace

@{
    ViewBag.Title = "ФПР в лицах";

}

<h2>ФПР в лицах</h2>

<h3>Вы действительно хотите удалить запись?</h3>
<div>
    <h4>Удаление</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FIO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Biography)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Biography)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Achivments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Achivments)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhotoPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhotoPath)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Назад", "Index")
        </div>
    }
</div>

SportSchoolApplication/Views/FPRInFaces/Details.cshtml
@model SportSchoolApplication.Models.FPRInFace

@{
    ViewBag.Title = "ФПР в лицах";

}

<h2>ФПР в лицах</h2>

<div>
    <h4>Детали:</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FIO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Biography)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Biography)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Achivments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Achivments)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhotoPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhotoPath)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Назад", "Index")
</p>

SportSchoolApplication/Views/FPRInFaces/Edit.cshtml
@model SportSchoolApplication.Models.FPRInFace

@{
    ViewBag.Title = "ФПР в лицах";
    string oldPhotoPath = Model.PhotoPath;
}

<h2>ФПР в лицах</h2>

@using (Html.BeginForm(Html.BeginForm("Edit", "FPRInFaces", FormMethod.Post, new { enctype = "multipart/form-data" })))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Редактирование</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <input type="hidden" name="oldPhotoPath" value=@oldPhotoPath />

    <div class="form-group">
        @Html.LabelFor(model => model.FIO, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FIO, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FIO, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Biography, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <textarea name="Biography" rows="5" class="form-control">@Model.Biography</textarea>
            @Html.ValidationMessageFor(model => model.Biography, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Achivments, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <textarea name="Achivments" rows="5" class="form-control">@Model.Achivments</textarea>
            @Html.ValidationMessageFor(model => model.Achivments, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IsCoach, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IsCoach, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IsCoach, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PhotoPath, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PhotoPath, new { htmlAttributes = new { type = "file" } })
            @Html.ValidationMessageFor(model => model.PhotoPath, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Сохранить" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

SportSchoolApplication/Views/FPRInFaces/Index.cshtml
@model IEnumerable<SportSchoolApplication.Models.FPRInFace>

@{
    ViewBag.Title = "ФПР в лицах";

}

<h2>ФПР в лицах</h2>

<p>
    @Html.ActionLink("Добавить запись", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FIO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Biography)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Achivments)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsCoach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhotoPath)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FIO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Biography)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Achivments)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsCoach)
            </td>
            <td>
                <img src="@item.PhotoPath" width="100px" height="100px" />
            </td>
            <td>
                @Html.ActionLink("Редактировать", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Детали", "Details", new { id = item.Id }) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>